-- 004_experiences.sql: Experience schema for FleetSeek DebugNote MVP-α
-- Adds: pgvector, experiences (STI), config_snapshots, experience_applications
-- Extends: robots with L2 fingerprint columns
-- Migrates: existing episodes → experiences (type='skill')

-- pgvector extension
CREATE EXTENSION IF NOT EXISTS vector;

-- robots: L2 physical fingerprint columns
ALTER TABLE robots ADD COLUMN IF NOT EXISTS serial_number TEXT;
ALTER TABLE robots ADD COLUMN IF NOT EXISTS mac_address TEXT;
ALTER TABLE robots ADD COLUMN IF NOT EXISTS hw_revision TEXT;
-- L1: application-layer ID (rbt_ + ULID), generated by API on robot register
ALTER TABLE robots ADD COLUMN IF NOT EXISTS fleetseek_id TEXT UNIQUE;

-- config_snapshots (L3 — mutable, versioned per robot)
CREATE TABLE IF NOT EXISTS config_snapshots (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  robot_id TEXT NOT NULL,            -- fleetseek_id (rbt_ + ULID)
  sdk_version TEXT,
  firmware_version TEXT,
  os_version TEXT,
  installed_packages JSONB DEFAULT '{}',
  config_hash TEXT,                  -- SHA256 of canonicalized config
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX idx_config_snapshots_robot ON config_snapshots(robot_id);
CREATE INDEX idx_config_snapshots_created ON config_snapshots(created_at DESC);

-- experiences: Single Table Inheritance base for SkillExperience + DebugExperience
CREATE TABLE IF NOT EXISTS experiences (
  id TEXT PRIMARY KEY,               -- exp_ + ULID

  type VARCHAR(20) NOT NULL CHECK (type IN ('skill', 'debug_note')),

  -- Ownership
  robot_id TEXT NOT NULL,            -- fleetseek_id (rbt_ + ULID)
  org_id TEXT,
  visibility VARCHAR(20) DEFAULT 'org' CHECK (visibility IN ('public', 'org', 'private')),

  -- Applicability (structured — natural-language-only is prohibited per schema rules)
  -- { robot_model, firmware_version_range, task_context, environment }
  applicability JSONB NOT NULL DEFAULT '{}',

  -- Provenance
  -- { source: 'human_uploaded'|'auto_harvested'|'migrated', session_id, collected_at }
  provenance JSONB NOT NULL DEFAULT '{}',

  -- Trust signals (A: applications, B: ai_review, C: human_signals)
  trust_signals JSONB NOT NULL DEFAULT '{
    "applications": {"total": 0, "successful": 0, "failed": 0},
    "ai_review": null,
    "human_signals": {"upvotes": 0, "downvotes": 0, "human_verifications": 0, "failed_applications": 0}
  }',
  -- Computed from trust_signals; never written directly
  trust_score FLOAT DEFAULT 0.0,

  -- Status lifecycle: candidate → ai_reviewed/flagged → human_reviewed → canonical
  status VARCHAR(20) DEFAULT 'candidate'
    CHECK (status IN ('candidate', 'ai_reviewed', 'flagged', 'human_reviewed', 'canonical')),

  -- Subtype-specific payload (JSONB; validated in app layer)
  -- skill:      { task_specification, episode_data_ref, outcome }
  -- debug_note: { symptoms, root_cause, resolution, failed_attempts }
  data JSONB NOT NULL DEFAULT '{}',

  -- Semantic embedding of symptoms.observed_behavior.text (1536 dims = text-embedding-ada-002)
  embedding vector(1536),

  -- Common display fields
  title TEXT,
  description TEXT,
  tags TEXT[] DEFAULT '{}',

  -- Stats
  view_count INTEGER DEFAULT 0,
  application_count INTEGER DEFAULT 0,

  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX idx_experiences_type ON experiences(type);
CREATE INDEX idx_experiences_robot_id ON experiences(robot_id);
CREATE INDEX idx_experiences_status ON experiences(status);
CREATE INDEX idx_experiences_created ON experiences(created_at DESC);
CREATE INDEX idx_experiences_trust_score ON experiences(trust_score DESC);
CREATE INDEX idx_experiences_tags ON experiences USING GIN(tags);
CREATE INDEX idx_experiences_data ON experiences USING GIN(data);
-- HNSW index for cosine similarity search (works on empty tables, better recall than ivfflat)
CREATE INDEX idx_experiences_embedding ON experiences USING hnsw (embedding vector_cosine_ops);

-- experience_applications: tracks intent + outcome for each application
CREATE TABLE IF NOT EXISTS experience_applications (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  experience_id TEXT NOT NULL REFERENCES experiences(id) ON DELETE CASCADE,

  -- Who applied
  robot_id TEXT NOT NULL,
  config_snapshot_id UUID REFERENCES config_snapshots(id) ON DELETE SET NULL,

  -- Pre-application intent timestamp (posted by Claude agent before attempting)
  intent_at TIMESTAMP WITH TIME ZONE,

  -- Outcome after execution
  outcome VARCHAR(20) CHECK (outcome IN ('success', 'failure', 'partial', 'skipped')),
  outcome_notes TEXT,

  session_id TEXT,
  applied_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX idx_experience_applications_experience ON experience_applications(experience_id);
CREATE INDEX idx_experience_applications_robot ON experience_applications(robot_id);
CREATE INDEX idx_experience_applications_outcome ON experience_applications(outcome);

-- Migrate existing episodes → experiences (type='skill')
-- Safe to run even if episodes is empty
INSERT INTO experiences (
  id,
  type,
  robot_id,
  visibility,
  applicability,
  provenance,
  status,
  data,
  title,
  created_at,
  updated_at
)
SELECT
  'exp_' || replace(gen_random_uuid()::text, '-', '') AS id,
  'skill' AS type,
  COALESCE(e.robot_id, 'rbt_unknown') AS robot_id,
  'public' AS visibility,
  jsonb_build_object(
    'robot_model', 'unknown',
    'task_context', e.task_name
  ) AS applicability,
  jsonb_build_object(
    'source', 'migrated',
    'original_episode_id', e.id::text,
    'original_post_id', e.post_id::text
  ) AS provenance,
  CASE WHEN e.success THEN 'human_reviewed' ELSE 'candidate' END AS status,
  jsonb_build_object(
    'task_specification', jsonb_build_object(
      'task_name', e.task_name,
      'task_category', e.task_category
    ),
    'episode_data_ref', jsonb_build_object(
      'hf_repo', e.hf_repo,
      'hf_episode_index', e.hf_episode_index,
      'lerobot_path', e.lerobot_path,
      'video_url', e.video_url,
      'thumbnail_url', e.thumbnail_url
    ),
    'outcome', jsonb_build_object(
      'success', e.success,
      'completion_rate', e.completion_rate,
      'failure_reason', e.failure_reason
    )
  ) AS data,
  p.title AS title,
  e.created_at,
  e.created_at AS updated_at
FROM episodes e
JOIN posts p ON p.id = e.post_id;
